name: ChromoCore
author: Chr0mosom3
version: 1.0
api-version: 1.17
website: ladeira.eu

main: eu.ladeira.chromo.Chromo

libraries:
- org.mongodb:mongodb-driver-sync:4.4.0

commands:
  spawn:
  reputation:
    aliases: rep
  guild:
    aliases: g
  endlock:
    aliases: el